info.onScore(100, function () {
    game.setGameOverEffect(true, effects.confetti)
    game.gameOver(true)
})
info.onLifeZero(function () {
    game.gameOver(false)
})
let mySprite = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
info.setLife(3)
tiles.setCurrentTilemap(tilemap`level2`)
mySprite.setStayInScreen(true)
scene.cameraFollowSprite(mySprite)
game.onUpdate(function () {
    mySprite.startEffect(effects.spray)
})
